version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../../:/var/www/html
      - ../nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      dockerfile: php.Dockerfile
      context: .
    volumes:
      - ../../:/var/www/html
    links:
      - db
  db:
    image: postgres:9.6
    volumes:
       - ../migrations:/migrations
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    
    
