version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../../:/var/www/html
      - ../nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm-alpine
    volumes:
      - ../../:/var/www/html