<?php
namespace app\common\base\BaseControllerTest;

use app\common\base\BaseModule;
use app\common\interfaces\ModuleInterface;

class BaseModuleChild extends BaseModule implements ModuleInterface {
  public function getPath (string $sub_path = null) {
    return __DIR__ . '/' . $sub_path;
  }

  public function resolveController (string $controller_path) {
    if ($controller_path === 'TEST_ACTION') {
      return [
        'path' => __DIR__ . '/BaseModuleTestController.php',
        'className' => 'app\common\base\BaseModuleTestController'
      ];
    } else if ($controller_path === 'TEST_ACTION_FILE_NOT_FOUND') {
      return [
        'path' => 'not-found',
        'className' => 'app\common\base\BaseModuleTestController'
      ];
    } else if ($controller_path === 'TEST_ACTION_CLASS_NOT_FOUND') {
      return [
        'path' => __DIR__ . '/BaseModuleTestController.php',
        'className' => 'app\common\base\BaseModuleTestControllerNotFound'
      ];
    } else {
      return parent::resolveController($controller_path); // TODO: Change the autogenerated stub
    }
  }
}
